name: Serve static filles
on: [push]

jobs:
  Serve:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
      - uses: actions/checkout@v3
      - run: |
          cd ./client
          npm i
          npm run serve --token ${{secrets.SURGE_TOKEN}}
