name: Serve static filles
on: [push]

jobs:
  Serve:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
      - run: cd client
      - name: Install deps
      - run: npm i
      - name: Build and serve
      - run: npm run serve
